logging:
    level:
        blog: WARN
        org: WARN
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password:
        url: jdbc:mysql://localhost:3306/gameguidesforus?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: DEBUG
            defer-datasource-initialization: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    sql:
        init:
            mode: always

#Cloudinary Properties
cloudinary:
    api-key:
    api-secret:
    cloud-name: